url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Amy!" # the name of your site, e.g. ACME Corp.
theme: null
sass:
  style: expanded